### ISSUE TITLE
issue with xml prettify

### ISSUE THREAD

**Issue by ghost** [WEGFan/Geometry-Dash-Savefile-Editor#1]
upon selecting option 4, it previously would confirm that the prettification was successful. now it gives the message "Geometry Dash Savefile Encrypter & Decrypter v1.1.2 by WEGFan Decryption code downloaded from https://pastebin.com/JakxXUVG by Absolute Gamer" and doesn't prettify the xml file. i've made sure the directories matched, and i didn't have any other programs open. 

really awesome program either way, although without this feature it's almost impossible to do anything

![i](https://user-images.githubusercontent.com/76858225/103450157-e020d780-4c77-11eb-9037-06bd6384e755.PNG)

**Comment by WEGFan** [comment]
That is just an option toggle. You need to first toggle on then decrypt, and the decrypted file will be prettified.

**Comment by ghost** [comment]
Yes, I'm aware of that. I decrypted the document prior to using that feature.
