### ISSUE TITLE
same issue

### ISSUE THREAD

**Issue by ghost** [WEGFan/Geometry-Dash-Savefile-Editor#2]
You closed my issue without allowing me to get back to you. I did decrypt the document before using the feature

![q](https://user-images.githubusercontent.com/76858225/106023199-340eb880-608c-11eb-85cc-1fe19ac17d8a.PNG)

**Comment by WEGFan** [comment]
You should first input 4, then input 2.

Make sure it shows `[Current: ON]` when you choose decrypt.
