### ISSUE TITLE
cant find decrypted files

### ISSUE THREAD

**Issue by sadohat** [WEGFan/Geometry-Dash-Savefile-Editor#4]
It says it decrypted the files but when looking at my gd folder it is not decrypted. @WEGFan where is the decrypted files stored?

**Comment by WEGFan** [comment]
The decrypted files are stored in the same folder as the executable you downloaded

**Comment by sadohat** [comment]
Its too big to open

**Comment by WEGFan** [comment]
You can use other text editors to open it, or delete the levels in saved levels in game first.
