### ISSUE TITLE
Request for fork that forces decryption

### ISSUE THREAD

**Issue by wialm** [WEGFan/Geometry-Dash-Savefile-Editor#5]
Since my savefile returns an error when it tries to decrypt the file (or with the savefile fixer), is there a way you could forcefully decrypt it, or is this not possible? are there any other alternatives you would suggest?
![image](https://user-images.githubusercontent.com/93901574/162671419-05abc447-7ade-4ed1-ad21-81c08686da26.png)

**Comment by WEGFan** [comment]
No, it's impossible to forcefully decrypt it. Can you send me the file to my discord so I can have a look at what happened?
